### ISSUE TITLE
Dota cannot launch or always crash on ubuntu

### ISSUE THREAD

**Issue by hafidzizzudin** [ValveSoftware/Dota-2#2587]
#### Your system information

<details><summary>System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/): </summary>

```
Computer Information:
Manufacturer: LENOVO
Model: Lancer 4A5
Form Factor: Laptop
No Touch Input Detected
Processor Information:
CPU Vendor: GenuineIntel
CPU Brand: Intel(R) Core(TM) i7-4510U CPU @ 2.00GHz
CPU Family: 0x6
CPU Model: 0x45
CPU Stepping: 0x1
CPU Type: 0x0
Speed: 3100 MHz
4 logical processors
2 physical processors
Hyper-threading: Supported
FCMOV: Supported
SSE2: Supported
SSE3: Supported
SSSE3: Supported
SSE4a: Unsupported
SSE41: Supported
SSE42: Supported
AES: Supported
AVX: Supported
AVX2: Supported
AVX512F: Unsupported
AVX512PF: Unsupported
AVX512ER: Unsupported
AVX512CD: Unsupported
AVX512VNNI: Unsupported
SHA: Unsupported
CMPXCHG16B: Supported
LAHF/SAHF: Supported
PrefetchW: Unsupported
Operating System Version:
Ubuntu 22.04.3 LTS (64 bit)
Kernel Name: Linux
Kernel Version: 6.2.0-35-generic
X Server Vendor: The X.Org Foundation
X Server Release: 12101004
X Window Manager: GNOME Shell
Steam Runtime Version: steam-runtime_0.20230801.56012
Video Card:
Driver: NVIDIA Corporation NVIDIA GeForce 840M/PCIe/SSE2
Driver Version: 4.6.0 NVIDIA 535.113.01
OpenGL Version: 4.6
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 59 Hz
VendorID: 0x10de
DeviceID: 0x1341
Revision Not Detected
Number of Monitors: 1
Number of Logical Video Cards: 1
Primary Display Resolution: 1920 x 1080
Desktop Resolution: 1920 x 1080
Primary Display Size: 12.17" x 6.81" (13.94" diag), 30.9cm x 17.3cm (35.4cm diag)
Primary Bus: PCI Express 4x
Primary VRAM: 4096 MB
Supported MSAA Modes: 2x 4x 8x 16x
Sound card:
Audio device: Intel Haswell HDMI
Memory:
RAM: 11844 Mb
VR Hardware:
VR Headset: None detected
Miscellaneous:
UI Language: English
LANG: en_US.UTF-8
Total Hard Disk Space Available: 120378 MB
Largest Free Hard Disk Block: 23235 MB
Storage:
Number of SSDs: 2
SSD sizes: 250G,0B
Number of HDDs: 0
Number of removable drives: 0
```

</details>

* Have you checked for system updates?: [Yes]
* Are you using the latest stable video driver available for your system? [Yes]
* Have you verified the game files?: [Yes]

#### Please describe your issue in as much detail as possible:
Whenever I start Dota, it won't launch. When I see the steam log, it fails when loading *.so files. Only several of them are successful.
Is there any suggestion that I can check or try to solve this issue? It just suddenly happened this afternoon in my local time UTC+7.

<details><summary>Terminal log</summary>

```
Fossilize INFO: Setting autogroup scheduling.
/bin/sh\0-c\0/home/hafidz/.steam/debian-installation/ubuntu12_32/reaper SteamLaunch AppId=570 -- /home/hafidz/.steam/debian-installation/ubuntu12_32/steam-launch-wrapper -- '/home/hafidz/.steam/debian-installation/steamapps/common/SteamLinuxRuntime_sniper'/_v2-entry-point --verb=waitforexitandrun --  '/home/hafidz/.steam/debian-installation/steamapps/common/dota 2 beta/game/dota.sh' +@panorama_min_comp_layer_dimension 0 -prewarm_panorama +dota_disable_controller_support 1 -autoconfig -safe\0
chdir "/home/hafidz/.steam/debian-installation/steamapps/common/dota 2 beta"
ERROR: ld.so: object '/home/hafidz/.steam/debian-installation/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/hafidz/.steam/debian-installation/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
ERROR: ld.so: object '/home/hafidz/.steam/debian-installation/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/hafidz/.steam/debian-installation/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/hafidz/.steam/debian-installation/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
pid 10923 != 10922, skipping destruction (fork without exec?)
pid 10924 != 10922, skipping destruction (fork without exec?)
Loaded /home/hafidz/.steam/debian-installation/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/libengine2.so, got 0x55e7138073c0
Using breakpad crash handler
[S_API] SteamAPI_Init(): Loaded '/home/hafidz/.steam/debian-installation/linux64/steamclient.so' OK.
Setting breakpad minidump AppID = 570
Forcing breakpad minidump interfaces to load
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
10/22 16:31:07 Init: Installing breakpad exception handler for appid(570)/version(8435322)/tid(10926)
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
SteamInternal_SetMinidumpSteamID:  Caching Steam ID:  76561198210789160 [API loaded yes]
SteamInternal_SetMinidumpSteamID:  Setting Steam ID:  76561198210789160
Setting breakpad minidump AppID = 373300
Loaded libSDL3.so.0, got 0x55e713af4c70
Loaded /home/hafidz/.steam/debian-installation/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/libtier0.so, got 0x55e7137f09f0
Loaded /home/hafidz/.steam/debian-installation/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/libfilesystem_stdio.so, got 0x55e713b31cb0
Loaded /home/hafidz/.steam/debian-installation/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/libinputsystem.so, got 0x55e713b34c50
Loaded /home/hafidz/.steam/debian-installation/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/liblocalize.so, got 0x55e713ba8640
Loaded /home/hafidz/.steam/debian-installation/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/librendersystemvulkan.so, got 0x55e713b939e0
Loaded /home/hafidz/.steam/debian-installation/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/libresourcesystem.so, got 0x55e713bc7f50
Loaded /home/hafidz/.steam/debian-installation/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/libschemasystem.so, got 0x55e713bb1490
MESA-INTEL: warning: Haswell Vulkan support is incomplete
Fossilize INFO: Overriding serialization path: "/home/hafidz/.steam/debian-installation/steamapps/shadercache/570/fozpipelinesv6/steamapprun_pipeline_cache".
crash_20231022163108_2.dmp[10949]: Uploading dump (out-of-process)
/tmp/dumps/crash_20231022163108_2.dmp
/home/hafidz/.steam/debian-installation/steamapps/common/dota 2 beta/game/dota.sh: line 122: 10926 Segmentation fault      (core dumped) ${STEAM_RUNTIME_PREFIX} ${GAME_DEBUGGER} "${GAMEROOT}"/${GAMEEXE} "$@"
crash_20231022163108_2.dmp[10949]: Finished uploading minidump (out-of-process): success = yes
crash_20231022163108_2.dmp[10949]: response: CrashID=bp-9129dff7-40ea-44fa-b822-18e742231022
crash_20231022163108_2.dmp[10949]: file ''/tmp/dumps/crash_20231022163108_2.dmp'', upload yes: ''CrashID=bp-9129dff7-40ea-44fa-b822-18e742231022''
pid 10949 != 10948, skipping destruction (fork without exec?)
Game 570 created interface STEAMAPPLIST_INTERFACE_VERSION001 / 
Game 570 created interface STEAMAPPS_INTERFACE_VERSION008 / 
Game 570 created interface STEAMHTMLSURFACE_INTERFACE_VERSION_005 / 
Game 570 created interface STEAMHTTP_INTERFACE_VERSION003 / 
Game 570 created interface STEAMINVENTORY_INTERFACE_V003 / 
Game 570 created interface STEAMMUSICREMOTE_INTERFACE_VERSION001 / 
Game 570 created interface STEAMMUSIC_INTERFACE_VERSION001 / 
Game 570 created interface STEAMPARENTALSETTINGS_INTERFACE_VERSION001 / 
Game 570 created interface STEAMREMOTESTORAGE_INTERFACE_VERSION016 / 
Game 570 created interface STEAMSCREENSHOTS_INTERFACE_VERSION003 / 
Game 570 created interface STEAMUGC_INTERFACE_VERSION018 / 
Game 570 created interface STEAMUSERSTATS_INTERFACE_VERSION012 / 
Game 570 created interface STEAMVIDEO_INTERFACE_V003 / 
Game 570 created interface SteamController008 / 
Game 570 created interface SteamFriends017 / 
Game 570 created interface SteamInput006 / 
Game 570 created interface SteamMatchGameSearch001 / 
Game 570 created interface SteamMatchMaking009 / 
Game 570 created interface SteamMatchMakingServers002 / 
Game 570 created interface SteamNetworking006 / 
Game 570 created interface SteamUser023 / 
Game 570 created interface SteamUser023 / User
Game 570 created interface SteamUtils010 / 
Game 570 method call count for IClientAppManager::GetCurrentLanguage : 1
Game 570 method call count for IClientAppManager::GetAppStateInfo : 1
Game 570 method call count for IClientUtils::RecordSteamInterfaceCreation : 24
Game 570 method call count for IClientUtils::IsSteamChina : 1
Game 570 method call count for IClientUtils::GetLauncherType : 1
Game 570 method call count for IClientUtils::GetSteamUILanguage : 1
Game 570 method call count for IClientUtils::GetAppID : 27
Game 570 method call count for IClientFriends::GetFriendPersonaName_Public : 2
Game 570 method call count for IClientUser::GetUserDataFolder : 1
Game 570 method call count for IClientUser::GetSteamID : 5
Uploaded AppInterfaceStats to Steam
```

</details>

#### Steps for reproducing this issue:

1. Open steam
2. Open dota 2
3. Ski[ vulkan shaders
![image](https://github.com/ValveSoftware/Dota-2/assets/25932466/304976da-0757-49c9-a742-39f26aec3f09)
4. Crash

**Comment by hafidzizzudin** [comment]
have been reinstalling dota but still no avail. Trying to debug with gdb got this result. Hopefully can be useful to get the root cause of this segvault.
<details><summary>Terminal log</summary>

```
GNU gdb (Ubuntu 12.1-0ubuntu1~22.04) 12.1
Copyright (C) 2022 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /home/hafidz/.steam/debian-installation/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/dota2...
(No debugging symbols found in /home/hafidz/.steam/debian-installation/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/dota2)
(gdb) r
Starting program: /home/hafidz/.steam/debian-installation/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/dota2 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[Detaching after vfork from child process 13956]
Loaded /home/hafidz/.steam/debian-installation/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/libengine2.so, got 0x555555599e20
Steam AppId(570), BreakpadId(373300)
InitSteamLogin_Internal: Initializing breakpad.
Using breakpad crash handler
[S_API] SteamAPI_Init(): Loaded '/home/hafidz/.steam/debian-installation/linux64/steamclient.so' OK.
Setting breakpad minidump AppID = 570
Forcing breakpad minidump interfaces to load
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
10/24 19:42:17 Init: Installing breakpad exception handler for appid(570)/version(8437856)/tid(13953)
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
SteamInternal_SetMinidumpSteamID:  Caching Steam ID:  76561198210789160 [API loaded yes]
SteamInternal_SetMinidumpSteamID:  Setting Steam ID:  76561198210789160
SteamAPI_Init succeeded.  SteamID is [U:1:250523432] (76561198210789160), AppID is 570
ResetBreakpadAppId: Universe is 1 (k_EUniversePublic)
ResetBreakpadAppId: Setting non standard break pad app id: 373300
Setting breakpad minidump AppID = 373300
CSteam3Client::Activate succeeded.  SteamID is [U:1:250523432] (76561198210789160), AppID is 570
Loaded libSDL3.so.0, got 0x55555588c400
[New Thread 0x7ffff5bff640 (LWP 13958)]
Loaded /home/hafidz/.steam/debian-installation/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/libtier0.so, got 0x5555555830e0
Visibility enabled.
Loaded /home/hafidz/.steam/debian-installation/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/libfilesystem_stdio.so, got 0x5555558db520
USRLOCAL path using Steam profile data folder:
/home/hafidz/.steam/debian-installation/userdata/250523432/570/local
Loaded /home/hafidz/.steam/debian-installation/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/libinputsystem.so, got 0x5555558edd10
Loaded /home/hafidz/.steam/debian-installation/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/liblocalize.so, got 0x55555594b0f0
Loaded /home/hafidz/.steam/debian-installation/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/librendersystemvulkan.so, got 0x55555591c4f0
Loaded /home/hafidz/.steam/debian-installation/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/libresourcesystem.so, got 0x555555947190
Loaded /home/hafidz/.steam/debian-installation/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/libschemasystem.so, got 0x555555916ee0
Enabling instance extension: VK_KHR_get_physical_device_properties2.
MESA-INTEL: warning: Haswell Vulkan support is incomplete
[New Thread 0x7fffd93ff640 (LWP 13965)]
Using VK_EXT_memory_budget set texture memory budget to 3970 MB.
HLSL SM6.0 level subgroup wave ops supported, subgroup size = 32
Vulkan physical device (2): supports shader clip distance: true
Vulkan physical device (2): using secondary command buffers: false
Using VK_EXT_memory_budget set texture memory budget to 1536 MB.
Vulkan physical device (0): supports shader clip distance: true
Vulkan physical device (0): using secondary command buffers: false
[New Thread 0x7ffff518e640 (LWP 13966)]
[New Thread 0x7fffea6c3640 (LWP 13967)]
[New Thread 0x7fffcbfff640 (LWP 13968)]
Loaded video settings config from 'cfg/video.txt'
Vulkan Physical Device: NVIDIA GeForce 840M
Initializing streaming texture manager.
Vulkan extension enabled: VK_KHR_swapchain
Vulkan extension enabled: VK_KHR_dedicated_allocation
Vulkan extension enabled: VK_KHR_descriptor_update_template
Vulkan extension enabled: VK_KHR_image_format_list
Vulkan extension enabled: VK_KHR_maintenance1
Vulkan extension enabled: VK_KHR_maintenance2
Vulkan extension enabled: VK_EXT_separate_stencil_usage
Vulkan extension enabled: VK_KHR_swapchain_mutable_format
Vulkan extension enabled: VK_EXT_multi_draw
Vulkan extension enabled: VK_EXT_load_store_op_none
Vulkan extension enabled: VK_KHR_pipeline_library
Vulkan extension enabled: VK_EXT_extended_dynamic_state
Vulkan extension enabled: VK_EXT_extended_dynamic_state2
Vulkan extension enabled: VK_KHR_dynamic_rendering
Vulkan extension enabled: VK_KHR_depth_stencil_resolve
Vulkan extension enabled: VK_KHR_create_renderpass2
Vulkan extension enabled: VK_EXT_graphics_pipeline_library
Vulkan extension enabled: VK_EXT_extended_dynamic_state3
Vulkan extension enabled: VK_KHR_shader_float16_int8
Vulkan extension enabled: VK_KHR_separate_depth_stencil_layouts
Vulkan extension enabled: VK_EXT_pipeline_creation_cache_control
Vulkan extension enabled: VK_KHR_buffer_device_address
Vulkan extension enabled: VK_KHR_shader_clock
Vulkan extension enabled: VK_EXT_memory_budget
Vulkan extension enabled: VK_KHR_draw_indirect_count
Vulkan extension enabled: VK_EXT_subgroup_size_control
VK_KHR_shader_float16_int8 does not support shaderFloat16, disabling.
[New Thread 0x7fffcb5fe640 (LWP 13970)]
[New Thread 0x7fffcadfd640 (LWP 13971)]
[New Thread 0x7fffca5fc640 (LWP 13972)]
[New Thread 0x7fffc9dfb640 (LWP 13974)]
[New Thread 0x7fffc92fa640 (LWP 13977)]
Fossilize INFO: Overriding serialization path: "/home/hafidz/.steam/debian-installation/steamapps/shadercache/570/fozpipelinesv6/steamapprun_pipeline_cache".
[New Thread 0x7fffc8af9640 (LWP 13978)]
VK_EXT_graphics_pipeline_library and dependent extensions enabled.
[New Thread 0x7fffab91e640 (LWP 13979)]
[New Thread 0x7fffaadff640 (LWP 13980)]
Vulkan Command Buffer Pool Threshold(1500)

Thread 1 "dota2" received signal SIGSEGV, Segmentation fault.
__memmove_avx_unaligned_erms () at ../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S:874
874	../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S: No such file or directory.
(gdb) bt
#0  __memmove_avx_unaligned_erms () at ../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S:874
#1  0x00007ffff7530f1c in ?? () from /home/hafidz/.steam/debian-installation/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/libtier0.so
#2  0x00007ffffffefc10 in ?? ()
#3  0x00007ffff784aeb8 in ?? () from /home/hafidz/.steam/debian-installation/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/libtier0.so
#4  0x0000000000000021 in ?? ()
#5  0x0000000000000000 in ?? ()
(gdb)
```


</details>

**Comment by hafidzizzudin** [comment]
already solved with the latest patch

**Comment by genghisun** [comment]
still same problem here in Ubuntu 20.04, can't launch dota2 for at least last two days.
