### ISSUE TITLE
Dota2 doesn't start on linux since Spring Cleaning Update

### ISSUE THREAD

**Issue by czarnyckm** [ValveSoftware/Dota-2#823]
Hi,
since few days I'm unable to start Dota2 on 64bit Debian Sid with Alsa.
I verified local content, but without effect.

``` console
./dota.sh: line 104:  7351 Segmentation fault      ${STEAM_RUNTIME_PREFIX} ${GAME_DEBUGGER} "${GAMEROOT}"/${GAMEEXE} $@
```

Other games works fine e.g.: cs:go or Xcom2. 

System Information:

```
Computer Information:
    Manufacturer:  Unknown
    Model:  Unknown
    Form Factor: Desktop
    No Touch Input Detected

Processor Information:
    CPU Vendor:  AuthenticAMD
    CPU Family:  0x15
    CPU Model:  0x2
    CPU Stepping:  0x0
    CPU Type:  0x0
    Speed:  4000 Mhz
    8 logical processors
    8 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Supported
    SSE41:  Supported
    SSE42:  Supported
    AES:  Supported
    AVX:  Supported
    CMPXCHG16B:  Supported
    LAHF/SAHF:  Supported
    PrefetchW:  Unsupported

Network Information:
    Network Speed:  

Operating System Version:
    Debian GNU/Linux unstable (sid) (64 bit)
    Kernel Name:  Linux
    Kernel Version:  4.5.0
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11802000
    X Window Manager:  KWin
    Steam Runtime Version:  steam-runtime-release_2016-02-23

Video Card:
    Driver:  NVIDIA Corporation GeForce GTX 960/PCIe/SSE2

    Driver Version:  4.5.0 NVIDIA 364.12
    OpenGL Version: 4.5
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 59 Hz
    VendorID:  0x10de
    DeviceID:  0x1401
    Number of Monitors:  1
    Number of Logical Video Cards:  1
    Primary Display Resolution:  2560 x 1440
    Desktop Resolution: 2560 x 1440
    Primary Display Size: 20.75" x 11.65"  (23.78" diag)
                                            52.7cm x 29.6cm  (60.4cm diag)
    Primary Bus: PCI Express 16x
    Primary VRAM: 4096 MB
    Supported MSAA Modes:  2x 4x 8x 16x 

Sound card:
    Audio device: 20K2

Memory:
    RAM:  32128 Mb

Miscellaneous:
    UI Language:  English
    LANG:  de_DE.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  614100 Mb
    Largest Free Hard Disk Block:  198617 Mb
    VR Headset: None detected

    Fri Apr  1 10:19:04 2016 GMT: file ''/tmp/dumps/crash_20160401121853_1.dmp'', upload yes: ''Discarded=1''
    Fri Apr  1 10:23:18 2016 GMT: file ''/tmp/dumps/crash_20160401122314_1.dmp'', upload yes: ''Discarded=1''
    Fri Apr  1 10:25:10 2016 GMT: file ''/tmp/dumps/crash_20160401122505_1.dmp'', upload yes: ''Discarded=1''
    Fri Apr  1 10:45:22 2016 GMT: file ''/tmp/dumps/crash_20160401124517_1.dmp'', upload yes: ''Discarded=1''
    Fri Apr  1 10:52:40 2016 GMT: file ''/tmp/dumps/assert_20160401125237_29.dmp'', upload yes: ''CrashID=bp-89b87289-51e1-4286-a2d9-aff7e2160401''
    Fri Apr  1 10:56:19 2016 GMT: file ''/tmp/dumps/crash_20160401125613_1.dmp'', upload yes: ''Discarded=1''
```

console.log:

``` console
GL_NVX_gpu_memory_info: AVAILABLE
GL_ATI_meminfo: UNAVAILABLE
GL_NVX_gpu_memory_info: Total Dedicated: 4194304, Total Avail: 4194304, Current Avail: 3659600
CreateDevice: Requested DX level 110, clamped to DX level 105
ERROR: HangWatchdogInternal_BeginScope() - Hang watchdog not implemented for this platform!
ERROR: HangWatchdogInternal_EndScope() - Hang watchdog not implemented for this platform!
---------------
Path ID:             File Path:
ADDONS               "/usr/local/games/SteamLibrary/SteamApps/common/dota 2 beta/game/dota_addons/"
CONTENT              "/usr/local/games/SteamLibrary/SteamApps/common/dota 2 beta/content/dota/"
CONTENT              "/usr/local/games/SteamLibrary/SteamApps/common/dota 2 beta/content/core/"
CONTENTADDONS        "/usr/local/games/SteamLibrary/SteamApps/common/dota 2 beta/content/dota_addons/"
CONTENTROOT          "/usr/local/games/SteamLibrary/SteamApps/common/dota 2 beta/content/"
DEFAULT_WRITE_PATH   "/usr/local/games/SteamLibrary/SteamApps/common/dota 2 beta/game/dota/pak01.vpk" (vpk) /usr/local/games/SteamLibrary/SteamApps/common/dota 2 beta/game/dota/pak01.vpk
DEFAULT_WRITE_PATH   "/usr/local/games/SteamLibrary/SteamApps/common/dota 2 beta/game/dota/"
EXECUTABLE_PATH      "/usr/local/games/SteamLibrary/SteamApps/common/dota 2 beta/game/bin/linuxsteamrt64/"
GAME                 "/usr/local/games/SteamLibrary/SteamApps/common/dota 2 beta/game/dota/pak01.vpk" (vpk) /usr/local/games/SteamLibrary/SteamApps/common/dota 2 beta/game/dota/pak01.vpk
GAME                 "/usr/local/games/SteamLibrary/SteamApps/common/dota 2 beta/game/core/pak01.vpk" (vpk) /usr/local/games/SteamLibrary/SteamApps/common/dota 2 beta/game/core/pak01.vpk
GAME                 "/usr/local/games/SteamLibrary/SteamApps/common/dota 2 beta/game/dota/"
GAME                 "/usr/local/games/SteamLibrary/SteamApps/common/dota 2 beta/game/core/"
GAMEBIN              "/usr/local/games/SteamLibrary/SteamApps/common/dota 2 beta/game/dota/bin/linuxsteamrt64/"
GAMEBIN              "/usr/local/games/SteamLibrary/SteamApps/common/dota 2 beta/game/dota/bin/"
GAMEBIN              "/usr/local/games/SteamLibrary/SteamApps/common/dota 2 beta/game/core/bin/linuxsteamrt64/"
GAMEBIN              "/usr/local/games/SteamLibrary/SteamApps/common/dota 2 beta/game/core/bin/"
GAMEROOT             "/usr/local/games/SteamLibrary/SteamApps/common/dota 2 beta/game/"
MOD                  "/usr/local/games/SteamLibrary/SteamApps/common/dota 2 beta/game/dota/pak01.vpk" (vpk) /usr/local/games/SteamLibrary/SteamApps/common/dota 2 beta/game/dota/pak01.vpk
MOD                  "/usr/local/games/SteamLibrary/SteamApps/common/dota 2 beta/game/dota/"
PLATFORM             "/usr/local/games/SteamLibrary/SteamApps/common/dota 2 beta/game/core/pak01.vpk" (vpk) /usr/local/games/SteamLibrary/SteamApps/common/dota 2 beta/game/core/pak01.vpk
PLATFORM             "/usr/local/games/SteamLibrary/SteamApps/common/dota 2 beta/game/core/"
SHADER_SOURCE        "/usr/local/games/SteamLibrary/SteamApps/common/dota 2 beta/src/shaders/dota/"
SHADER_SOURCE        "/usr/local/games/SteamLibrary/SteamApps/common/dota 2 beta/src/shaders/core/"
SHADER_SOURCE        "/usr/local/games/SteamLibrary/SteamApps/common/dota 2 beta/src/shaders/dota_addons/"
SHADER_SOURCE        "/usr/local/games/SteamLibrary/SteamApps/common/dota 2 beta/src/shaders/dota_core/"
SHADER_SOURCE_MOD    "/usr/local/games/SteamLibrary/SteamApps/common/dota 2 beta/src/shaders/dota/"
SHADER_SOURCE_ROOT   "/usr/local/games/SteamLibrary/SteamApps/common/dota 2 beta/src/shaders/"
command line arguments:
-con_logfile
Network System Initialized
192.168.178.20: enp6s0
127.0.0.1: lo
Physics Console Communications is not initialized
Game supporting (2) split screen players
```

Strace:

```
6876  close(9)                          = 0
6876  open("/usr/lib/locale/en_US.UTF-8/LC_COLLATE", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
6876  open("/usr/lib/locale/en_US.utf8/LC_COLLATE", O_RDONLY|O_CLOEXEC) = 9
6876  fstat(9, {st_mode=S_IFREG|0644, st_size=1243766, ...}) = 0
6876  mmap(NULL, 1243766, PROT_READ, MAP_PRIVATE, 9, 0) = 0x7f46d0207000
6876  close(9)                          = 0
6876  open("/usr/lib/locale/en_US.UTF-8/LC_TIME", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
6876  open("/usr/lib/locale/en_US.utf8/LC_TIME", O_RDONLY|O_CLOEXEC) = 9
6876  fstat(9, {st_mode=S_IFREG|0644, st_size=2454, ...}) = 0
6876  mmap(NULL, 2454, PROT_READ, MAP_PRIVATE, 9, 0) = 0x7f46d01ff000
6876  close(9)                          = 0
6876  open("/usr/lib/locale/en_US.UTF-8/LC_NUMERIC", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
6876  open("/usr/lib/locale/en_US.utf8/LC_NUMERIC", O_RDONLY|O_CLOEXEC) = 9
6876  fstat(9, {st_mode=S_IFREG|0644, st_size=54, ...}) = 0
6876  mmap(NULL, 54, PROT_READ, MAP_PRIVATE, 9, 0) = 0x7f46d01f7000
6876  close(9)                          = 0
6876  open("/usr/lib/locale/en_US.UTF-8/LC_CTYPE", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
6876  open("/usr/lib/locale/en_US.utf8/LC_CTYPE", O_RDONLY|O_CLOEXEC) = 9
6876  fstat(9, {st_mode=S_IFREG|0644, st_size=317692, ...}) = 0
6876  mmap(NULL, 317692, PROT_READ, MAP_PRIVATE, 9, 0) = 0x7f46d01a7000
6876  close(9)                          = 0
6876  uname({sysname="Linux", nodename="czarnyckm", ...}) = 0
6876  fstat(1, {st_mode=S_IFIFO|0600, st_size=0, ...}) = 0
6876  write(1, "Linux 4.5.0 #1 SMP PREEMPT Mon M"..., 63) = 63
6876  close(1)                          = 0
6862  <... read resumed> "Linux 4.5.0 #1 SMP PREEMPT Mon M"..., 4096) = 63
6876  close(2)                          = 0
6876  exit_group(0)                     = ?
6862  close(67)                         = 0
6862  wait4(6876,  <unfinished ...>
6876  +++ exited with 0 +++
6862  <... wait4 resumed> [{WIFEXITED(s) && WEXITSTATUS(s) == 0}], 0, NULL) = 6876
6862  --- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=6876, si_uid=1001, si_status=0, si_utime=0, si_stime=1} ---
6862  stat("/etc/localtime", {st_mode=S_IFREG|0644, st_size=2335, ...}) = 0
6862  prctl(PR_SET_DUMPABLE, 1)         = 0
6862  gettid()                          = 6862
6862  mmap(NULL, 16384, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f12cf14b000
6862  pipe([67, 68])                    = 0
6862  clone( <unfinished ...>
6872  <... futex resumed> )             = -1 ETIMEDOUT (Connection timed out)
6872  futex(0x563fe838f3c8, FUTEX_WAKE_PRIVATE, 1) = 0
6872  futex(0x563fe838f3f4, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 489, {1459506338, 85247000}, ffffffff <unfinished ...>
6862  <... clone resumed> child_stack=0x7f12cf14ee80, flags=CLONE_FS|CLONE_FILES|CLONE_UNTRACED) = 6877
6862  prctl(PR_SET_PTRACER, 6877)       = -1 EINVAL (Invalid argument)
6862  write(68, "a", 1)                 = 1
6862  wait4(6877,  <unfinished ...>
6872  <... futex resumed> )             = -1 ETIMEDOUT (Connection timed out)
6862  <... wait4 resumed> [{WIFEXITED(s) && WEXITSTATUS(s) == 1}], __WALL, NULL) = 6877
6872  futex(0x563fe838f3c8, FUTEX_WAKE_PRIVATE, 1 <unfinished ...>
6862  close(67 <unfinished ...>
6872  <... futex resumed> )             = 0
6862  <... close resumed> )             = 0
6872  futex(0x563fe838f3f4, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 491, {1459506338, 95487000}, ffffffff <unfinished ...>
6862  close(68)                         = 0
6862  write(2, "No minidump written, nothing to "..., 40) = 40
6862  munmap(0x7f12cf14b000, 16384)     = 0
6862  rt_sigaction(SIGSEGV, {SIG_DFL, [SEGV], SA_RESTORER|SA_RESTART, 0x7f12ce3fa2a0}, {0x7f12ca20e340, [ILL ABRT BUS FPE SEGV], SA_RESTORER|SA_STACK|SA_SIGINFO, 0x7f12ce3fa2a0}, 8) = 0
6862  rt_sigreturn({mask=[]})           = 0
6862  --- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0} ---
6866  <... poll resumed> )              = ? <unavailable>
6874  +++ killed by SIGSEGV +++
6873  +++ killed by SIGSEGV +++
6872  +++ killed by SIGSEGV +++
6871  +++ killed by SIGSEGV +++
6870  +++ killed by SIGSEGV +++
6869  +++ killed by SIGSEGV +++
6868  +++ killed by SIGSEGV +++
6867  +++ killed by SIGSEGV +++
6866  +++ killed by SIGSEGV +++
6865  +++ killed by SIGSEGV +++
6864  +++ killed by SIGSEGV +++
6863  +++ killed by SIGSEGV +++
6862  +++ killed by SIGSEGV +++
6859  <... wait4 resumed> [{WIFSIGNALED(s) && WTERMSIG(s) == SIGSEGV}], 0, NULL) = 6862
6859  rt_sigaction(SIGINT, {SIG_DFL, [], SA_RESTORER, 0x7f957b83a2a0}, {0x44a2f0, [], SA_RESTORER, 0x7f957b83a2a0}, 8) = 0
6859  open("/usr/share/locale/de_DE.UTF-8/LC_MESSAGES/bash.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
6859  open("/usr/share/locale/de_DE.utf8/LC_MESSAGES/bash.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
6859  open("/usr/share/locale/de_DE/LC_MESSAGES/bash.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
6859  open("/usr/share/locale/de.UTF-8/LC_MESSAGES/bash.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
6859  open("/usr/share/locale/de.utf8/LC_MESSAGES/bash.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
6859  open("/usr/share/locale/de/LC_MESSAGES/bash.mo", O_RDONLY) = 3
6859  fstat(3, {st_mode=S_IFREG|0644, st_size=92884, ...}) = 0
6859  mmap(NULL, 92884, PROT_READ, MAP_PRIVATE, 3, 0) = 0x7f957c01f000
6859  close(3)                          = 0
6859  open("/usr/share/locale/de_DE.UTF-8/LC_MESSAGES/libc.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
6859  open("/usr/share/locale/de_DE.utf8/LC_MESSAGES/libc.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
6859  open("/usr/share/locale/de_DE/LC_MESSAGES/libc.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
6859  open("/usr/share/locale/de.UTF-8/LC_MESSAGES/libc.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
6859  open("/usr/share/locale/de.utf8/LC_MESSAGES/libc.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
6859  open("/usr/share/locale/de/LC_MESSAGES/libc.mo", O_RDONLY) = 3
6859  fstat(3, {st_mode=S_IFREG|0644, st_size=155302, ...}) = 0
6859  mmap(NULL, 155302, PROT_READ, MAP_PRIVATE, 3, 0) = 0x7f957b7df000
6859  close(3)                          = 0
6859  brk(0x7d5000)                     = 0x7d5000
6859  write(2, "./dota.sh: Zeile 104:  6862 Spei"..., 121) = 121
6859  rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
6859  --- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_KILLED, si_pid=6862, si_uid=1001, si_status=SIGSEGV, si_utime=173, si_stime=239} ---
6859  wait4(-1, 0x7fff04932910, WNOHANG, NULL) = -1 ECHILD (No child processes)
6859  rt_sigreturn({mask=[]})           = 0
6859  rt_sigprocmask(SIG_BLOCK, [CHLD], [], 8) = 0
6859  rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
6859  read(255, "exit $STATUS\n", 3332) = 13
6859  rt_sigprocmask(SIG_BLOCK, [CHLD], [], 8) = 0
6859  rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
6859  exit_group(139)                   = ?
6859  +++ exited with 139 +++
```

**Comment by gdrewb-valve** [comment]
The Steam failure reports that have CrashIDs are ones that were recorded at Valve.  The one you have is a problem in the Steam client itself with the hardware survey and isn't related to Dota.  When you have crashes that aren't recorded they're most often problems in the video driver, but I have no proof of that.  If you're familiar with gdb at all you can start Dota in gdb and then at least get an idea of where the crash is happening.

**Comment by czarnyckm** [comment]
Backtrace:

``` console
Program received signal SIGSEGV, Segmentation fault.
strlen () at ../sysdeps/x86_64/strlen.S:106
106     in ../sysdeps/x86_64/strlen.S
(gdb) bt
#0  strlen () at ../sysdeps/x86_64/strlen.S:106
#1  0x00007ffff72eae2e in __GI___strdup (s=0x0) at strdup.c:41
#2  0x00007fffef65eb92 in ?? () from /usr/local/games/SteamLibrary/SteamApps/common/dota 2 beta/game/bin/linuxsteamrt64/libSDL2-2.0.so.0
#3  0x00007fffef65ed1b in ?? () from /usr/local/games/SteamLibrary/SteamApps/common/dota 2 beta/game/bin/linuxsteamrt64/libSDL2-2.0.so.0
#4  0x00007fffef5c77b0 in ?? () from /usr/local/games/SteamLibrary/SteamApps/common/dota 2 beta/game/bin/linuxsteamrt64/libSDL2-2.0.so.0
#5  0x00007fffef5c46f7 in ?? () from /usr/local/games/SteamLibrary/SteamApps/common/dota 2 beta/game/bin/linuxsteamrt64/libSDL2-2.0.so.0
#6  0x00007fffdfb96d16 in ?? () from /usr/local/games/SteamLibrary/SteamApps/common/dota 2 beta/game/bin/linuxsteamrt64/libsoundsystem.so
#7  0x00007fffdfb96f85 in ?? () from /usr/local/games/SteamLibrary/SteamApps/common/dota 2 beta/game/bin/linuxsteamrt64/libsoundsystem.so
#8  0x00007fffdfb933fa in ?? () from /usr/local/games/SteamLibrary/SteamApps/common/dota 2 beta/game/bin/linuxsteamrt64/libsoundsystem.so
#9  0x00007fffdfb2644b in ?? () from /usr/local/games/SteamLibrary/SteamApps/common/dota 2 beta/game/bin/linuxsteamrt64/libsoundsystem.so
#10 0x00007fffdfb1de64 in ?? () from /usr/local/games/SteamLibrary/SteamApps/common/dota 2 beta/game/bin/linuxsteamrt64/libsoundsystem.so
#11 0x00007fffdfaf23bb in ?? () from /usr/local/games/SteamLibrary/SteamApps/common/dota 2 beta/game/bin/linuxsteamrt64/libsoundsystem.so
#12 0x00007ffff5f8bbde in ?? () from /usr/local/games/SteamLibrary/SteamApps/common/dota 2 beta/game/bin/linuxsteamrt64/libengine2.so
#13 0x00007ffff623d1b2 in ?? () from /usr/local/games/SteamLibrary/SteamApps/common/dota 2 beta/game/bin/linuxsteamrt64/libengine2.so
#14 0x00007ffff623d940 in ?? () from /usr/local/games/SteamLibrary/SteamApps/common/dota 2 beta/game/bin/linuxsteamrt64/libengine2.so
#15 0x00007ffff5ee312f in ?? () from /usr/local/games/SteamLibrary/SteamApps/common/dota 2 beta/game/bin/linuxsteamrt64/libengine2.so
#16 0x00007ffff62ba6f2 in ?? () from /usr/local/games/SteamLibrary/SteamApps/common/dota 2 beta/game/bin/linuxsteamrt64/libengine2.so
#17 0x00007ffff5ee0539 in ?? () from /usr/local/games/SteamLibrary/SteamApps/common/dota 2 beta/game/bin/linuxsteamrt64/libengine2.so
#18 0x00007ffff623cf10 in ?? () from /usr/local/games/SteamLibrary/SteamApps/common/dota 2 beta/game/bin/linuxsteamrt64/libengine2.so
#19 0x00007ffff623dc86 in ?? () from /usr/local/games/SteamLibrary/SteamApps/common/dota 2 beta/game/bin/linuxsteamrt64/libengine2.so
#20 0x00007ffff5ed14ae in ?? () from /usr/local/games/SteamLibrary/SteamApps/common/dota 2 beta/game/bin/linuxsteamrt64/libengine2.so
#21 0x00007ffff5ed3829 in ?? () from /usr/local/games/SteamLibrary/SteamApps/common/dota 2 beta/game/bin/linuxsteamrt64/libengine2.so
#22 0x00007ffff5ed3ac7 in Source2Main () from /usr/local/games/SteamLibrary/SteamApps/common/dota 2 beta/game/bin/linuxsteamrt64/libengine2.so
#23 0x0000555555555101 in ?? ()
#24 0x00007ffff728d780 in __libc_start_main (main=0x555555554f90, argc=1, argv=0x7fffffffdc48, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffffffdc38) at ../csu/libc-start.c:291
#25 0x0000555555555219 in _start ()
```

**Comment by gdrewb-valve** [comment]
Thanks, I'll pass this on to the SDL team.  They just added some extra ALSA output enumeration and it looks like they have a bug.

**Comment by czarnyckm** [comment]
I can confirm after remove libSDL2-2.0.so.0 from game/bin/linuxsteamrt64/ directory the Dota2 start again. Thanks

**Comment by czarnyckm** [comment]
I want just lets you known that todays update breaked dota2 again. 

Backtrace:

``` console
Program received signal SIGSEGV, Segmentation fault.
strlen () at ../sysdeps/x86_64/strlen.S:106
106     ../sysdeps/x86_64/strlen.S: Datei oder Verzeichnis nicht gefunden.
(gdb) bt
#0  strlen () at ../sysdeps/x86_64/strlen.S:106
#1  0x00007ffff72eae2e in __GI___strdup (s=0x0) at strdup.c:41
#2  0x00007fffef65eb12 in ?? () from /usr/local/games/SteamLibrary/SteamApps/common/dota 2 beta/game/bin/linuxsteamrt64/libSDL2-2.0.so.0
#3  0x00007fffef65ec9b in ?? () from /usr/local/games/SteamLibrary/SteamApps/common/dota 2 beta/game/bin/linuxsteamrt64/libSDL2-2.0.so.0
#4  0x00007fffef5c77b0 in ?? () from /usr/local/games/SteamLibrary/SteamApps/common/dota 2 beta/game/bin/linuxsteamrt64/libSDL2-2.0.so.0
#5  0x00007fffef5c46f7 in ?? () from /usr/local/games/SteamLibrary/SteamApps/common/dota 2 beta/game/bin/linuxsteamrt64/libSDL2-2.0.so.0
#6  0x00007fffdfb91d16 in ?? () from /usr/local/games/SteamLibrary/SteamApps/common/dota 2 beta/game/bin/linuxsteamrt64/libsoundsystem.so
#7  0x00007fffdfb91f85 in ?? () from /usr/local/games/SteamLibrary/SteamApps/common/dota 2 beta/game/bin/linuxsteamrt64/libsoundsystem.so
#8  0x00007fffdfb8e3fa in ?? () from /usr/local/games/SteamLibrary/SteamApps/common/dota 2 beta/game/bin/linuxsteamrt64/libsoundsystem.so
#9  0x00007fffdfb2144b in ?? () from /usr/local/games/SteamLibrary/SteamApps/common/dota 2 beta/game/bin/linuxsteamrt64/libsoundsystem.so
#10 0x00007fffdfb18e64 in ?? () from /usr/local/games/SteamLibrary/SteamApps/common/dota 2 beta/game/bin/linuxsteamrt64/libsoundsystem.so
#11 0x00007fffdfaed3bb in ?? () from /usr/local/games/SteamLibrary/SteamApps/common/dota 2 beta/game/bin/linuxsteamrt64/libsoundsystem.so
#12 0x00007ffff5f8befe in ?? () from /usr/local/games/SteamLibrary/SteamApps/common/dota 2 beta/game/bin/linuxsteamrt64/libengine2.so
#13 0x00007ffff623d4d2 in ?? () from /usr/local/games/SteamLibrary/SteamApps/common/dota 2 beta/game/bin/linuxsteamrt64/libengine2.so
#14 0x00007ffff623dc60 in ?? () from /usr/local/games/SteamLibrary/SteamApps/common/dota 2 beta/game/bin/linuxsteamrt64/libengine2.so
#15 0x00007ffff5ee312f in ?? () from /usr/local/games/SteamLibrary/SteamApps/common/dota 2 beta/game/bin/linuxsteamrt64/libengine2.so
#16 0x00007ffff62baa12 in ?? () from /usr/local/games/SteamLibrary/SteamApps/common/dota 2 beta/game/bin/linuxsteamrt64/libengine2.so
#17 0x00007ffff5ee0539 in ?? () from /usr/local/games/SteamLibrary/SteamApps/common/dota 2 beta/game/bin/linuxsteamrt64/libengine2.so
#18 0x00007ffff623d230 in ?? () from /usr/local/games/SteamLibrary/SteamApps/common/dota 2 beta/game/bin/linuxsteamrt64/libengine2.so
#19 0x00007ffff623dfa6 in ?? () from /usr/local/games/SteamLibrary/SteamApps/common/dota 2 beta/game/bin/linuxsteamrt64/libengine2.so
#20 0x00007ffff5ed14ae in ?? () from /usr/local/games/SteamLibrary/SteamApps/common/dota 2 beta/game/bin/linuxsteamrt64/libengine2.so
#21 0x00007ffff5ed3829 in ?? () from /usr/local/games/SteamLibrary/SteamApps/common/dota 2 beta/game/bin/linuxsteamrt64/libengine2.so
#22 0x00007ffff5ed3ac7 in Source2Main () from /usr/local/games/SteamLibrary/SteamApps/common/dota 2 beta/game/bin/linuxsteamrt64/libengine2.so
#23 0x0000555555555101 in ?? ()
#24 0x00007ffff728d780 in __libc_start_main (main=0x555555554f90, argc=1, argv=0x7fffffffdc78, init=<optimized out>, fini=<optimized out>, 
    rtld_fini=<optimized out>, stack_end=0x7fffffffdc68) at ../csu/libc-start.c:291
#25 0x0000555555555219 in _start ()
Backtrace:
```

**Comment by gdrewb-valve** [comment]
I don't believe we've shipped a fix, you just worked around it locally, didn't you?

**Comment by czarnyckm** [comment]
After the fix dota2 worked well till today.

The problem occured on the two computers with sid debian+ alsa 

1st: Creative Xfi + usb-audio + nvidia hdmi
2nd Creative Audigy 2zs + nvidia hdmi

 To be able to play dota today we must to delete libSDL again.

**Comment by gdrewb-valve** [comment]
That all sounds correct.  When we ship the fix we'll close this issue.

**Comment by gdrewb-valve** [comment]
I think the fix has shipped, is this still occurring?

**Comment by czarnyckm** [comment]
everything fine now. than you

**Comment by gdrewb-valve** [comment]
Thanks, closing.
