### ISSUE TITLE
Stuck on exit dialog

### ISSUE THREAD

**Issue by vadi2** [ValveSoftware/Dota-2#994]
Sometimes the game gets stuck on the exit dialog.

![screenshot from 2016-08-19 13-12-37](https://cloud.githubusercontent.com/assets/110988/17797770/f326f110-660e-11e6-892f-9ebe88e2f56e.png)

```
(gdb) bt
#0  0x00007f7f2f1389cd in pthread_join (threadid=140183394092800, thread_return=0x0) at pthread_join.c:90
#1  0x00007f7f27f7a25e in ?? () from /home/vadi/.local/share/Steam/SteamApps/common/dota 2 beta/game/bin/linuxsteamrt64/libSDL2-2.0.so.0
#2  0x00007f7f27f1d8ab in ?? () from /home/vadi/.local/share/Steam/SteamApps/common/dota 2 beta/game/bin/linuxsteamrt64/libSDL2-2.0.so.0
#3  0x00007f7f27f1e658 in ?? () from /home/vadi/.local/share/Steam/SteamApps/common/dota 2 beta/game/bin/linuxsteamrt64/libSDL2-2.0.so.0
#4  0x00007f7f1a3b1231 in ?? () from /home/vadi/.local/share/Steam/SteamApps/common/dota 2 beta/game/bin/linuxsteamrt64/libsoundsystem.so
#5  0x00007f7f1a33651e in ?? () from /home/vadi/.local/share/Steam/SteamApps/common/dota 2 beta/game/bin/linuxsteamrt64/libsoundsystem.so
#6  0x00007f7f1a30b7ee in ?? () from /home/vadi/.local/share/Steam/SteamApps/common/dota 2 beta/game/bin/linuxsteamrt64/libsoundsystem.so
#7  0x00007f7f1a33f2e1 in ?? () from /home/vadi/.local/share/Steam/SteamApps/common/dota 2 beta/game/bin/linuxsteamrt64/libsoundsystem.so
#8  0x00007f7f2b88180d in ?? () from /home/vadi/.local/share/Steam/SteamApps/common/dota 2 beta/game/bin/linuxsteamrt64/libengine2.so
#9  0x00007f7f2b8820df in ?? () from /home/vadi/.local/share/Steam/SteamApps/common/dota 2 beta/game/bin/linuxsteamrt64/libengine2.so
#10 0x00007f7f2b5e7751 in ?? () from /home/vadi/.local/share/Steam/SteamApps/common/dota 2 beta/game/bin/linuxsteamrt64/libengine2.so
#11 0x00007f7f2b5116b0 in ?? () from /home/vadi/.local/share/Steam/SteamApps/common/dota 2 beta/game/bin/linuxsteamrt64/libengine2.so
#12 0x00007f7f2b511b27 in Source2Main () from /home/vadi/.local/share/Steam/SteamApps/common/dota 2 beta/game/bin/linuxsteamrt64/libengine2.so
#13 0x000056281de68219 in ?? ()
#14 0x00007f7f2f36d830 in __libc_start_main (main=0x56281de68130, argc=1, argv=0x7ffe66161678, init=<optimised out>, fini=<optimised out>, 
    rtld_fini=<optimised out>, stack_end=0x7ffe66161668) at ../csu/libc-start.c:291
#15 0x000056281de682ad in _start ()
(gdb) 
```

```
Computer Information:
    Manufacturer:  Unknown
    Model:  Unknown
    Form Factor: Desktop
    No Touch Input Detected

Processor Information:
    CPU Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0x2a
    CPU Stepping:  0x7
    CPU Type:  0x0
    Speed:  3300 Mhz
    4 logical processors
    4 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported
    AES:  Supported
    AVX:  Supported
    CMPXCHG16B:  Supported
    LAHF/SAHF:  Supported
    PrefetchW:  Unsupported

Network Information:
    Network Speed:  

Operating System Version:
    Ubuntu 16.04 LTS (64 bit)
    Kernel Name:  Linux
    Kernel Version:  4.4.0-34-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11803000
    X Window Manager:  Compiz
    Steam Runtime Version:  steam-runtime-beta-release_2016-06-15

Video Card:
    Driver:  NVIDIA Corporation GeForce GTX 780 Ti/PCIe/SSE2

    Driver Version:  4.5.0 NVIDIA 364.16
    OpenGL Version: 4.5
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 60 Hz
    VendorID:  0x10de
    DeviceID:  0x100a
    Revision Not Detected
    Number of Monitors:  1
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1920 x 1080
    Desktop Resolution: 1920 x 1080
    Primary Display Size: 20.47" x 11.42"  (23.43" diag)
                                            52.0cm x 29.0cm  (59.5cm diag)
    Primary Bus: PCI Express 16x
    Primary VRAM: 3072 MB
    Supported MSAA Modes:  2x 4x 8x 16x 

Sound card:
    Audio device: Realtek ALC889

Memory:
    RAM:  7966 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_AU.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  104566 Mb
    Largest Free Hard Disk Block:  15930 Mb
    VR Headset: None detected

Recent Failure Reports:
```

**Comment by ramma** [comment]
This might be the same as #603, which a few people have said is still happening.

**Comment by vadi2** [comment]
Probably is, I've had it a while. Though today I only played one game and
watched a few. Let me know if I can provide any more information on the
issue.

**Comment by gdrewb-valve** [comment]
This is being tracked in #793, assigned to the SDL dev.
